<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GCF [
<!ELEMENT GCF (Pod)+>
<!ELEMENT Pod (Region)+>
<!ELEMENT Region (Datacenter)+>
<!ELEMENT Datacenter (Vblock)+>
<!ELEMENT Vblock (Cluster)+>
<!ELEMENT Cluster (Module)+>
<!ELEMENT Module (Option)*>
<!ELEMENT Option EMPTY>
<!ATTLIST Pod Code CDATA #REQUIRED>
<!ATTLIST Pod Exclude CDATA #IMPLIED>
<!ATTLIST Region Code CDATA #REQUIRED>
<!ATTLIST Datacenter Code CDATA #REQUIRED>
<!ATTLIST Vblock Code CDATA #REQUIRED>
<!ATTLIST Cluster Code CDATA #REQUIRED>
<!ATTLIST Module Code CDATA #REQUIRED>
<!ATTLIST Module Count CDATA #IMPLIED>
<!ATTLIST Module Primary CDATA #IMPLIED>
<!ATTLIST Option Code CDATA #REQUIRED>
]>

<GCF>
	<Pod Code="POD01">
		<Region Code="TOKYO">
			<Datacenter Code="TKY01">
				<Vblock Code="VB01">
					<Cluster Code="AMP">
						<Module Code="ESX_AGENT" Count="2"/>
						<Module Code="VB_MGMT"/>
					</Cluster>
					<Cluster Code="MGMT">
						<Module Code="ESX_AGENT" Count="4"/>
						<Module Code="VB_MGMT_VSM" Vblock="VB01"/>
						<Module Code="VB_MGMT_VSM" Vblock="VB02"/>
						<Module Code="VB_MGMT_VSM" Vblock="VB07"/>
						<Module Code="VB_MGMT_VSM" Vblock="VB09"/>

						<Module Code="POD_MGMT"/>
						<Module Code="REGION_MGMT"/>
						<Module Code="DC_MGMT"/>
						<Module Code="IAAS_MGMT"/>
						<Module Code="DAAS_MGMT"/>

						<Module Code="DC_MGMT" Replica="VB08"/>
						<Module Code="VB_MGMT" Replica="VB08">
							<Option Code="VC" Exclude="true"/>
							<Option Code="VCDB" Exclude="true"/>
							<Option Code="VUM" Exclude="true"/>
						</Module>
						<Module Code="VB_MGMT_VSM" Replica="VB08"/>

						<Module Code="VB_MGMT" Replica="VB09"/>
						<Module Code="VB_MGMT_VSM" Replica="VB09"/>
					</Cluster>
				</Vblock>
				<Vblock Code="VB02">
					<Cluster Code="AMP">
						<Module Code="VB_MGMT">
							<Option Code="N1KV"/>
						</Module>
						<Module Code="ESX_AGENT" Count="2"/>
					</Cluster>
				</Vblock>
			</Datacenter>

			<Datacenter Code="TKY02">
				<Vblock Code="VB07">
					<Cluster Code="AMP">
						<Module Code="ESX_AGENT" Count="2"/>
						<Module Code="VB_MGMT"/>
						<Module Code="DC_MGMT"/>
					</Cluster>
				</Vblock>
			</Datacenter>
		</Region>

		<Region Code="OSAKA">
			<Datacenter Code="OSK01">
				<Vblock Code="VB08">
					<Cluster Code="AMP">
						<Module Code="ESX_AGENT" Count="2"/>
						<Module Code="VB_MGMT"/>
					</Cluster>
					<Cluster Code="MGMT">
						<Module Code="ESX_AGENT" Count="4"/>
						<Module Code="VB_MGMT_VSM" Vblock="VB08"/>

						<Module Code="REGION_MGMT"/>
						<Module Code="DC_MGMT"/>

						<Module Code="POD_MGMT" Replica="VB01"/>
						<Module Code="DC_MGMT" Replica="VB01"/>
						<Module Code="VB_MGMT" Replica="VB01"> 
							<Option Code="VC" Exclude="true"/>
							<Option Code="VCDB" Exclude="true"/>
							<Option Code="VUM" Exclude="true"/>
						</Module>
						<Module Code="VB_MGMT_VSM" Replica="VB01"/> 
						<Module Code="IAAS_MGMT" Replica="VB01"/>
						<Module Code="DAAS_MGMT" Replica="VB01"/>

						<Module Code="VB_MGMT" Replica="VB02"> 
	 						<Option Code="N1KV"/>
						</Module>
						<Module Code="VB_MGMT_VSM" Replica="VB02"/> 

						<Module Code="DC_MGMT" Replica="VB07"/>
						<Module Code="VB_MGMT" Replica="VB07"/> 
						<Module Code="VB_MGMT_VSM" Replica="VB07"/> 
					</Cluster>
				</Vblock>
				<Vblock Code="VB09">
					<Cluster Code="AMP">
						<Module Code="ESX_AGENT" Count="2"/>
						<Module Code="VB_MGMT"/>
					</Cluster>
				</Vblock>
			</Datacenter>
		</Region>
	</Pod>
	<Pod Code="POD03" Exclude="true">
		<Region Code="POC01">
			<Datacenter Code="CBC01">
				<Vblock Code="VB10">
					<Cluster Code="AMP">
						<Module Code="VB_MGMT"/>
					</Cluster>
				</Vblock>
			</Datacenter>
		</Region>
		<Region Code="POC02">
			<Datacenter Code="CBC01">
				<Vblock Code="VB11">
					<Cluster Code="AMP">
						<Module Code="VB_MGMT"/>
					</Cluster>
				</Vblock>
			</Datacenter>
		</Region>
	</Pod>
</GCF>
