<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GCF [
<!ELEMENT GCF (Module)+>
<!ELEMENT Module (Application)+>
<!ELEMENT Application (Node)*>
<!ELEMENT Node (Replica)*>
<!ELEMENT Replica EMPTY>
<!ATTLIST Module Code CDATA #REQUIRED>
<!ATTLIST Module Description CDATA #REQUIRED>
<!ATTLIST Application Code CDATA #REQUIRED>
<!ATTLIST Application Description CDATA #REQUIRED>
<!ATTLIST Application Optional CDATA #IMPLIED>
<!ATTLIST Application Replicated CDATA #IMPLIED>
<!ATTLIST Application Cluster CDATA #IMPLIED>
<!ATTLIST Node Code CDATA #REQUIRED>
<!ATTLIST Node Replicated CDATA #IMPLIED>
<!ATTLIST Replica Code CDATA #REQUIRED>
]>
<GCF>
	<Module Code="POD_MGMT" Description="Management applications deployed for each Pod">
		<Application Code="HYPRC" Description="Hyperic Server" Replicated="true"/>
		<Application Code="SPRI" Description="Splunk Index Server" Replicated="true"/>
		<Application Code="UM" Description="vCloud Usage Meter"/>
		<Application Code="VCO" Description="vCenter Orchestrator" Replicated="true"/>
		<Application Code="VCOPS" Description="vCenter Operation Manager" Replicated="true">
			<Node Code="01"/>
			<Node Code="02"/>
		</Application>
	</Module>

	<Module Code="REGION_MGMT" Description="Management applications deployed for each Region">
		<Application Code="SRM" Description="VMware Site Recovery Manager" Cluster="AMP"/>
		<Application Code="VSRA" Description="vSphere Replicator Appliance">
			<Node Code="01"/> 
			<Node Code="02"/> 
		</Application>
		<Application Code="SRM_EDGE" Description="vShield Edge for SRM Test Failover"/>
		<Application Code="DS" Description="DeepSecurity Manager"/>
		<Application Code="DSDB" Description="DeepSecurity Manager Database"/>
		<Application Code="AD_IAAS" Description="Active Directory Domain Controller for IAAS">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
	</Module>

	<Module Code="DC_MGMT" Description="Management applications deployed for each Datacenter">
		<Application Code="AD" Description="Active Directory Domain Controller">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
		<Application Code="SSO" Description="vCenter SSO Server" Replicated="true">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
		<Application Code="ESRS" Description="EMC ESRS Server" Cluster="AMP">
			<Node Code="01"/> 
			<Node Code="02"/> 
			<Node Code="03"/> 
		</Application>
	</Module>

	<Module Code="VB_MGMT" Description="Management applications deployed for each Vblock">
		<Application Code="VC" Description="vCenter" Replicated="true">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
		<Application Code="VCDB" Description="vCenter Database" Replicated="true">
			<Node Code="A">
				<Replica Code="M"/> 
				<Replica Code="LS"/>
			</Node> 
			<Node Code="B" Replicated="false"/>
		</Application>
		<Application Code="VUM" Description="vCenter Update Manager" Replicated="true">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
		<Application Code="SPLF" Description="Splunk Forwarder"  Replicated="true"/>
		<Application Code="AM" Description="EMC Array Manager"/>
		<Application Code="N1KV" Description="Cisco Nexus 1000V Switch" Optional="true"  Replicated="true">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
	</Module>

	<Module Code="VB_MGMT_VSM" Description="vShield Manager for AMP vCenter">
		<Application Code="VSM" Description="vShield Manager"  Replicated="true"/>
	</Module>

	<Module Code="ESX_AGENT" Description="ESXi Agent VM">
		<Application Code="VADP" Description="VADP appliance for Avamar"/>
		<Application Code="DSVA" Description="DeepSecurity vApp"/>
	</Module>

	<Module Code="IAAS_MGMT" Description="Management applications for IAAS">
		<Application Code="VCD" Description="vCloud Director Cell" Replicated="true">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
		<Application Code="VCDDB" Description="vCloud Director Database" Replicated="true">
			<Node Code="A"> 
				<Replica Code="M"/> 
				<Replica Code="LS"/>
			</Node>
			<Node Code="B" Replicated="false"/>
		</Application>
		<Application Code="CB" Description="vCenter Chargeback" Replicated="true">
			<Node Code="01"/> 
			<Node Code="02"/> 
			<Node Code="03"/> 
		</Application>
		<Application Code="LB" Description="vShield Edge load balancer" Replicated="true">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
	</Module>

	<Module Code="DAAS_MGMT" Description="Management applications for DAAS">
		<Application Code="VCD" Description="vCloud Director Cell" Replicated="true">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
		<Application Code="VCDDB" Description="vCloud Director Database" Replicated="true">
			<Node Code="A">
				<Replica Code="M"/> 
				<Replica Code="LS"/>
			</Node>	
			<Node Code="B">
				<Replica Code=""/>
			</Node> 
		</Application>
		<Application Code="LB" Description="vShield Edge load balancer">
			<Node Code="A"/> 
			<Node Code="B"/> 
		</Application>
	</Module>
</GCF>
